capstone-mindmate/mindmate-backend

- src/main/java/com/mindmate/mindmate_server/user/domain/CounselingField.java
- src/main/java/com/mindmate/mindmate_server/user/domain/CounselingStyle.java
- src/main/java/com/mindmate/mindmate_server/user/domain/ListenerCounselingField.java
- src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
- src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
- src/main/java/com/mindmate/mindmate_server/user/domain/User.java
#1 
1. user 엔티티 추가
2. 리스너 엔티티 추가
3. 관련 enum 데이터 추가
1. 스피커 엔티티 추가
2. user - 리스너 - 스피커 데이터 및 매핑 관계 점검
3. 글로벌 예외 처리 추가
> Feat#1 기초 user 엔티티 및 리스너 엔티티 추가

- src/main/java/com/mindmate/mindmate_server/config/JpaConfig.java
- src/main/java/com/mindmate/mindmate_server/global/config/JpaConfig.java
- src/main/java/com/mindmate/mindmate_server/global/entity/BaseTimeEntity.java
- src/main/java/com/mindmate/mindmate_server/global/exception/CommonErrorCode.java
- src/main/java/com/mindmate/mindmate_server/global/exception/CustomException.java
- src/main/java/com/mindmate/mindmate_server/global/exception/ErrorCode.java
- src/main/java/com/mindmate/mindmate_server/global/exception/ErrorResponse.java
- src/main/java/com/mindmate/mindmate_server/global/exception/GlobalExceptionHandler.java
- src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
- src/main/java/com/mindmate/mindmate_server/user/domain/SpeakerProfile.java
- src/main/java/com/mindmate/mindmate_server/user/domain/User.java
#1 
스피커 엔티티 추가
글로벌 예외 처리 추가에 따른 customException, response 등 기초 예외 코드
> Feat#1 스피커 엔티티 및 글로벌 예외 처리 추가

- build.gradle
- src/main/java/com/mindmate/mindmate_server/auth/util/SecurityUtil.java
- src/main/java/com/mindmate/mindmate_server/global/exception/ProfileErrorCode.java
- src/main/java/com/mindmate/mindmate_server/review/domain/Review.java
- src/main/java/com/mindmate/mindmate_server/review/dto/ReviewResponse.java
- src/main/java/com/mindmate/mindmate_server/review/repository/ReviewRepository.java
- src/main/java/com/mindmate/mindmate_server/user/controller/AdminCertificationController.java
- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileController.java
- src/main/java/com/mindmate/mindmate_server/user/domain/Badge.java
- src/main/java/com/mindmate/mindmate_server/user/domain/ListenerProfile.java
- src/main/java/com/mindmate/mindmate_server/user/domain/SpeakerProfile.java
- src/main/java/com/mindmate/mindmate_server/user/dto/AdminCertificationListResponse.java
- src/main/java/com/mindmate/mindmate_server/user/dto/AdminCertificationResponse.java
- src/main/java/com/mindmate/mindmate_server/user/dto/BadgeResponse.java
- src/main/java/com/mindmate/mindmate_server/user/dto/BaseProfileResponse.java
- src/main/java/com/mindmate/mindmate_server/user/dto/CertificationProcessRequest.java
- src/main/java/com/mindmate/mindmate_server/user/dto/CertificationUpdateRequest.java
- src/main/java/com/mindmate/mindmate_server/user/dto/ListenerProfileResponse.java
- src/main/java/com/mindmate/mindmate_server/user/dto/ListenerProfileUpdateRequest.java
- src/main/java/com/mindmate/mindmate_server/user/dto/SpeakerProfileResponse.java
- src/main/java/com/mindmate/mindmate_server/user/dto/SpeakerProfileUpdateRequest.java
- src/main/java/com/mindmate/mindmate_server/user/repository/ListenerRepository.java
- src/main/java/com/mindmate/mindmate_server/user/repository/SpeakerRepository.java
- src/main/java/com/mindmate/mindmate_server/user/service/CertificationService.java
- src/main/java/com/mindmate/mindmate_server/user/service/CertificationServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileService.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/service/UserService.java
- src/main/java/com/mindmate/mindmate_server/user/service/UserServiceImpl.java
#5 프로필 관리 및 인증 시스템
기본 도메인 추가
기본 dto 추가
ProfileService 수정 로직 추가
CertificationService 자격 인증 로직 추가
ProfileController 수정 엔드포인트 추가
AdminCertificationController 관리자 인증 엔드포인트 추가
매개변수로 받는 값들 RequestBody로 변경
의논 필요한 세부 로직
그 외 수정 필요한 부분 refactor 예정
리뷰 역할별 가져오기
> [Feat #5] 프로필 관리 및 인증 시스템

- src/main/java/com/mindmate/mindmate_server/auth/util/JwtTokenProvider.java
- src/main/java/com/mindmate/mindmate_server/chat/controller/WebSocketChatController.java
- src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
- src/main/java/com/mindmate/mindmate_server/global/exception/ReportErrorCode.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingService.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/report/controller/AdminReportController.java
- src/main/java/com/mindmate/mindmate_server/report/controller/ReportController.java
- src/main/java/com/mindmate/mindmate_server/report/domain/Report.java
- src/main/java/com/mindmate/mindmate_server/report/domain/ReportReason.java
- src/main/java/com/mindmate/mindmate_server/report/domain/ReportTarget.java
- src/main/java/com/mindmate/mindmate_server/report/dto/ReportDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/report/dto/ReportRequest.java
- src/main/java/com/mindmate/mindmate_server/report/dto/ReportResponse.java
- src/main/java/com/mindmate/mindmate_server/report/dto/ReportStatisticsResponse.java
- src/main/java/com/mindmate/mindmate_server/report/dto/SuspensionRequest.java
- src/main/java/com/mindmate/mindmate_server/report/dto/UnsuspendRequest.java
- src/main/java/com/mindmate/mindmate_server/report/repository/ReportRepository.java
- src/main/java/com/mindmate/mindmate_server/report/repository/ReportRepositoryCustom.java
- src/main/java/com/mindmate/mindmate_server/report/repository/ReportRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/report/service/AdminReportService.java
- src/main/java/com/mindmate/mindmate_server/report/service/AdminServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/report/service/ReportService.java
- src/main/java/com/mindmate/mindmate_server/report/service/ReportServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/report/util/SuspensionScheduler.java
- src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
- src/main/java/com/mindmate/mindmate_server/user/domain/User.java
- src/main/java/com/mindmate/mindmate_server/user/repository/UserRepository.java
- src/main/java/com/mindmate/mindmate_server/user/service/UserService.java
- src/main/java/com/mindmate/mindmate_server/user/service/UserServiceImpl.java
#35 
1. 신고 엔티티 및 dto 설계
2. 신고하기 기능
3. admin 신고 관련 기능
4. matching 가져오는 서비스 코드 하나 추가
> [Feat#35] 신고 기능

- src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
- src/main/java/com/mindmate/mindmate_server/report/dto/ReportRequest.java
- src/main/java/com/mindmate/mindmate_server/report/dto/UnsuspendRequest.java
- src/main/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
- src/test/java/com/mindmate/mindmate_server/profile/service/ProfileServiceTest.java
- src/test/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/report/service/ReportServiceImplTest.java
#38 
1. 사용자 신고 기능 테스트
2. 관리자 신고 기능 테스트
> [Feat#38] 신고 테스트 코드

- src/main/java/com/mindmate/mindmate_server/matching/controller/MatchingController.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/Matching.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingCreateRequest.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingUpdateRequest.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/WaitingUserResponse.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepository.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepositoryCustom.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/WaitingUserRepository.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumer.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingService.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/service/RedisMatchingService.java
- src/test/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/matching/service/MatchingEventProducerTest.java
- src/test/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/matching/service/RedisMatchingServiceTest.java
#42 
- 매칭 서비스 테스트
- 매칭 서비스 리팩토링
- 매칭 시 카테고리 선택 변경
- 레디스 & 카프카 테스트
- 자동매칭 관련은 요구사항 확정시 추가로 진행할 계획
> [Test#42] 매칭 테스트

- src/main/java/com/mindmate/mindmate_server/chat/controller/WebSocketChatController.java
- src/main/java/com/mindmate/mindmate_server/chat/dto/ChatEvent.java
- src/main/java/com/mindmate/mindmate_server/chat/dto/ChatEventType.java
- src/main/java/com/mindmate/mindmate_server/chat/dto/PresenceRequest.java
- src/main/java/com/mindmate/mindmate_server/chat/dto/ReactionRequest.java
- src/main/java/com/mindmate/mindmate_server/chat/service/ChatEventPublisher.java
- src/main/java/com/mindmate/mindmate_server/chat/service/ChatPresenceService.java
- src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/chat/util/ChatMessageListener.java
- src/main/java/com/mindmate/mindmate_server/chat/util/WebSocketDestinationResolver.java
- src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
- src/main/resources/templates/websocket-test.html
#40 
1. redis sub/puh 퍼블리싱
2. 중복 코드 제거
3. redis 이벤트 장애 대응
> [Feat#40] 채팅 redis 로직 수정 및 리팩토링

- src/main/java/com/mindmate/mindmate_server/matching/controller/MatchingController.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/Matching.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/MatchingStatus.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/MatchingType.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/WaitingUser.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingService.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/service/RedisMatchingService.java
#47 
- 가중치 계산 로직
- 가중치 기반 선택 로직
- 랜덤 매칭 로직
- 트랜잭션 관리를 개선하려고 구현 하고 있었는데 스프링 내장 시스템(또는 레디스)을 쓸지, 그냥 카프카를 쓸지 고민이 됩니다..
> [Update#47] 랜덤 매칭 로직 변경

- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumer.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/service/RedisMatchingService.java
- src/test/java/com/mindmate/mindmate_server/matching/service/MatchingEventConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/matching/service/RedisMatchingServiceTest.java
#51 
- 매칭 서비스의 랜덤매칭 테스트
- 레디스 매칭 서비스의 계산 및 선택 로직 테스트
> [Test#51] 랜덤매칭 로직 테스트

- src/main/java/com/mindmate/mindmate_server/global/exception/MagazineErrorCode.java
- src/main/java/com/mindmate/mindmate_server/magazine/controller/AdminMagazineController.java
- src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineController.java
- src/main/java/com/mindmate/mindmate_server/magazine/domain/Magazine.java
- src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineImage.java
- src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineLike.java
- src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineStatus.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCategoryStatistics.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCreateRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineResponse.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineSearchFilter.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepository.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepositoryCustom.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineService.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineStatisticsService.java
- src/main/java/com/mindmate/mindmate_server/user/domain/User.java
#45 
1. 매거진 조회/생성/수정/삭제/필터링
2. 관리자 매거진 조회/관리/통계
> [Feat#45] 매거진 기능 설계

- .gitignore
- src/main/java/com/mindmate/mindmate_server/magazine/domain/Magazine.java
- src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineImage.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCreateRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineImageService.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatPresenceServiceTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/MagazineImageServiceIntegrationTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineImageServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineStatisticsServiceTest.java
#55 
1. 매거진 업데이트(pending 상태로), 이미지 업로드 수정(원자적 처리)
2. 매거진 기능 테스트
3. 매거진 이미지 기능 테스트
이미지 업로드하는 기능이 외부 라이브러리를 써서 webp 변환하고 하는건데 이거를 단위테스트에서 진행할 수가 없음
통합테스트로 해보려 했는데 모르겠음
> [Test#55] 매거진 테스트

- src/main/java/com/mindmate/mindmate_server/point/dto/PointAddRequest.java
- src/main/java/com/mindmate/mindmate_server/point/dto/PointRequest.java
- src/main/java/com/mindmate/mindmate_server/point/dto/PointUseRequest.java
- src/main/java/com/mindmate/mindmate_server/point/service/PointServiceImpl.java
- src/test/java/com/mindmate/mindmate_server/point/service/PointServiceImplTest.java
#76 
- 포인트 시스템 테스트코드 작성
- 포인트 시스템 리팩토링
> [Test#76] 포인트 시스템 테스트

- src/main/java/com/mindmate/mindmate_server/global/config/KafkaConfig.java
- src/main/java/com/mindmate/mindmate_server/global/util/RedisKeyManager.java
- src/main/java/com/mindmate/mindmate_server/global/util/SlackNotifier.java
- src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineController.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineEngagementEvent.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineEngagementRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepository.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineEngagementConsumer.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityService.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineService.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/util/MagazineDataCleanUpScheduler.java
- src/main/java/com/mindmate/mindmate_server/magazine/util/MagazinePopularityDecayScheduler.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
#71 
1. 매거진 활동 내용 받아서 처리하기
2. 매거진 활동에 따른 인기도 계산
3. 인기 매거진 조회
4. (추가) 매거진 작성/수정 시 관리자 슬랙 알림
> [Feat#71] 인기 매거진 선정

- src/main/java/com/mindmate/mindmate_server/auth/service/AuthServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/chat/controller/ChatController.java
- src/main/java/com/mindmate/mindmate_server/chat/dto/ChatRoomNotificationEvent.java
- src/main/java/com/mindmate/mindmate_server/chat/service/ChatServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/emoticon/service/AdminEmoticonService.java
- src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonService.java
- src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/global/dto/FileInfo.java
- src/main/java/com/mindmate/mindmate_server/global/exception/CommonErrorCode.java
- src/main/java/com/mindmate/mindmate_server/global/service/FileStorageService.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineImageService.java
- src/test/java/com/mindmate/mindmate_server/emoticon/service/AdminEmoticonServiceTest.java
- src/test/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceTest.java
#82 
- 파일 처리 로직 통일 (매거진, 이모티콘)
- 이모티콘 서비스 중복 로직 제거
- 이모티콘 테스트 코드
> [Feat#82] 이모티콘 리팩토링 및 테스트 코드

- src/main/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumer.java
- src/test/java/com/mindmate/mindmate_server/chat/service/AdminFilteringServiceTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/AesGcmEncryptionServiceTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/AhoCorasickMatcherTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatNotificationConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatRoomCloseNotificationConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatServiceTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ContentFilterServiceTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/CustomFormServiceTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/FilteringEventConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/FilteringWordServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/MessageEncryptConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ToastBoxConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ToastBoxServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/UnreadConsumerTest.java
> [Test#86] 채팅 관련 테스트 코드

- src/main/java/com/mindmate/mindmate_server/global/exception/ReviewErrorCode.java
- src/main/java/com/mindmate/mindmate_server/report/domain/ReportTarget.java
- src/main/java/com/mindmate/mindmate_server/report/repository/ReportRepository.java
- src/main/java/com/mindmate/mindmate_server/report/service/ReportService.java
- src/main/java/com/mindmate/mindmate_server/report/service/ReportServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/review/controller/AdminReviewController.java
- src/main/java/com/mindmate/mindmate_server/review/dto/ReviewRequest.java
- src/main/java/com/mindmate/mindmate_server/review/dto/ReviewResponse.java
- src/main/java/com/mindmate/mindmate_server/review/repository/ReviewRedisRepository.java
- src/main/java/com/mindmate/mindmate_server/review/repository/ReviewRepository.java
- src/main/java/com/mindmate/mindmate_server/review/repository/ReviewRepositoryCustom.java
- src/main/java/com/mindmate/mindmate_server/review/repository/ReviewRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/review/service/AdminReviewService.java
- src/main/java/com/mindmate/mindmate_server/review/service/AdminReviewServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewService.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/domain/Profile.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileService.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
#87 
- 리뷰 로직 개선
- 페이징 성능 개선
- 주석 제거
> [Refact#87] 리뷰 관련 리팩토링

- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/review/controller/AdminReviewController.java
- src/main/java/com/mindmate/mindmate_server/review/service/AdminReviewServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewService.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewServiceImpl.java
- src/test/java/com/mindmate/mindmate_server/profile/service/ProfileServiceTest.java
- src/test/java/com/mindmate/mindmate_server/review/service/AdminReviewServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/review/service/ReviewServiceTest.java
> [Test#97] 리뷰 테스트

- src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/chat/service/ResponseTimeCalculationConsumer.java
- src/main/java/com/mindmate/mindmate_server/magazine/domain/MagazineContent.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineEngagementRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineImageRepository.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineContentService.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineStatisticsService.java
- src/main/java/com/mindmate/mindmate_server/report/dto/ReportRequest.java
- src/main/resources/static/magazine-test.html
- src/test/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineContentServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineEngagementConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineImageServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/report/service/ReportServiceImplTest.java
#94 
1. 채팅방 종료 순환 참조 해결
2. 매거진 리팩토링 및 업데이트
3. 매거진 테스트
> [Test, Update#94] 매거진 테스트 코드

- src/main/java/com/mindmate/mindmate_server/matching/controller/MatchingController.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/Matching.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/MatchingStatus.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/WaitingUser.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/AutoMatchingRequest.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingAcceptedEvent.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingSearchRequest.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/WaitingUserResponse.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepository.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/service/RedisMatchingService.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewDataService.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewService.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
#85 
- 중복 코드 분리
- 트랜잭션 관리
- 순환참조 해결
- 주석 제거
> [Refact#85] 매칭 리팩토링

- src/main/java/com/mindmate/mindmate_server/matching/controller/MatchingController.java
- src/main/java/com/mindmate/mindmate_server/notification/controller/AdminNotificationController.java
- src/main/java/com/mindmate/mindmate_server/notification/controller/FCMController.java
- src/main/java/com/mindmate/mindmate_server/notification/controller/NotificationController.java
- src/main/java/com/mindmate/mindmate_server/point/controller/PointController.java
- src/main/java/com/mindmate/mindmate_server/review/controller/AdminReviewController.java
- src/main/java/com/mindmate/mindmate_server/review/controller/ReviewController.java
- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileController.java
#112 api 수정
- 프로필
- 리뷰
- 매칭
- 알림
- 포인트
> [Update#112] api 수정

- build.gradle
- src/main/java/com/mindmate/mindmate_server/chat/util/WebSocketDestinationResolver.java
- src/main/java/com/mindmate/mindmate_server/emoticon/controller/EmoticonPopularityController.java
- src/main/java/com/mindmate/mindmate_server/emoticon/domain/UserEmoticon.java
- src/main/java/com/mindmate/mindmate_server/emoticon/dto/EmoticonCount.java
- src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonInteractionService.java
- src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonPopularityService.java
- src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/global/util/RedisKeyManager.java
- src/main/java/com/mindmate/mindmate_server/global/util/SlackNotifier.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineContentService.java
- src/main/java/com/mindmate/mindmate_server/report/service/ReportServiceImpl.java
- src/main/resources/static/websocket-test.html
1. 인기 이모티콘 선정 방식
2. 인기 이모티콘 조회
3. (추가) report 시 slacknotify
> [Feat#110] 인기 이모티콘 처리

- src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileController.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileService.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
#122 
1. 본인 프로필 인증 정보로 조회
2. cors 설정
> [Feat#122] 본인 프로필 조회

- src/main/java/com/mindmate/mindmate_server/auth/service/AuthServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/chat/dto/ChatRoomResponse.java
- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
#122 
1. 프로필 미작성 예외처리 삭제
2. 채팅방에 카테고리 데이터 추가
> [Feat#122] 프로필 미작성, 채팅방 데이터 수정

- src/main/java/com/mindmate/mindmate_server/global/exception/MagazineErrorCode.java
- src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineController.java
- src/main/java/com/mindmate/mindmate_server/magazine/domain/Magazine.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineCreateRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineResponse.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepository.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineService.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/domain/RoleType.java
#122 
1. 내가 작성한 매거진
2. 좋아요 누른 매거진
> [Feat#122] 매거진 조회 기능 추가

- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileImageController.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileImageService.java
> [Fix#133] 프로필 이미지 오류 해결

- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
- src/main/java/com/mindmate/mindmate_server/global/config/WebMvcConfig.java
- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileController.java
- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileImageController.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileImageService.java
- src/main/resources/static/websocket-test.html
#122 
1. 이미지 처리 path 충돌 및 에러 발생 해결
2. 프로필 이미지 엔티티 변경에 따라 채팅방 목록 querydsl 에러 해결
> [Feat#122] 이미지 처리, 채팅방 목록 오류 해결

- src/main/java/com/mindmate/mindmate_server/matching/domain/MatchingCategory.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileImageService.java
> [Fix#133] 카테고리 수정

- src/main/java/com/mindmate/mindmate_server/global/util/RedisKeyManager.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/report/domain/ReportTarget.java
- src/main/java/com/mindmate/mindmate_server/report/service/ReportServiceImpl.java
- src/main/resources/static/magazine-test.html
- src/main/resources/static/websocket-test.html
#122 
1. 매거진 부제목 처리
2. 매거진 신고 처리
> [Feat#122] QA/QC 업데이트

- .gitignore
- src/main/java/com/mindmate/mindmate_server/global/exception/MatchingErrorCode.java
- src/main/java/com/mindmate/mindmate_server/matching/controller/MatchingController.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepository.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/WaitingUserRepository.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingService.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileImageController.java
#133 
- 테스트를 위한 gitignore 추가
- 매칭방 내역 조회
- 현재 이미지 조회
> [Fix#133] 매칭 관련 수정 및 프로필 이미지 조회

- src/main/java/com/mindmate/mindmate_server/magazine/controller/MagazineController.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/magazine/repository/MagazineRepository.java
- src/main/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/report/controller/ReportController.java
- src/main/java/com/mindmate/mindmate_server/user/controller/ProfileImageController.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileImageService.java
#122 
1. 프로필 기본 이미지 중복 처리 해결
2. 매거진 상세 조회 추가 데이터 및 엔티티 그래프 적용
> [Feat#122] 프로필 기본 이미지 처리, 매거진 상세 조회 수정

- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
#122 
1. 채팅방 조회 오류 해결
2. 매칭 성사 시 채팅방 상태 변경
> [Feat#122] 채팅방 querydsl 

- src/main/java/com/mindmate/mindmate_server/global/exception/PaymentErrorCode.java
- src/main/java/com/mindmate/mindmate_server/payment/controller/AdminProductController.java
- src/main/java/com/mindmate/mindmate_server/payment/domain/PaymentProduct.java
- src/main/java/com/mindmate/mindmate_server/payment/dto/PaymentProductRequest.java
- src/main/java/com/mindmate/mindmate_server/payment/repository/PaymentProductRepository.java
- src/main/java/com/mindmate/mindmate_server/payment/service/PaymentService.java
- src/main/java/com/mindmate/mindmate_server/payment/service/PaymentServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/review/dto/ReviewListResponse.java
- src/main/java/com/mindmate/mindmate_server/review/service/ReviewServiceImpl.java
#133 
- 상품 등록 및 관리
- 리뷰 오류 고치기
- 동시성 처리
- cascade
> [Fix#133] 상품 등록 및 관리

- src/main/java/com/mindmate/mindmate_server/chat/dto/ChatRoomDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
> [Update] : 채팅방 입장 시 프로필 이미지 추가

- src/main/java/com/mindmate/mindmate_server/review/domain/Review.java
#159 
- 익명 리뷰시 true값 적용 안 됨 해결
> [fix#159] 익명 리뷰 에러 해결

- src/main/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/magazine/dto/MagazineUpdateRequest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatSearchServiceTest.java
- src/test/java/com/mindmate/mindmate_server/emoticon/service/AdminEmoticonServiceTest.java
- src/test/java/com/mindmate/mindmate_server/emoticon/service/EmoticonInteractionServiceTest.java
- src/test/java/com/mindmate/mindmate_server/emoticon/service/EmoticonPopularityServiceTest.java
- src/test/java/com/mindmate/mindmate_server/emoticon/service/EmoticonServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineContentServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineEngagementConsumerTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineImageServiceTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazinePopularityServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/magazine/service/MagazineServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/report/service/AdminReportServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/report/service/ReportServiceImplTest.java
#178 
1. 신고
2. 이모티콘
3. 매거진
기존 테스트 코드 개선 및 작성하지 않았던 기능들 추가
> [Feat#178] 신고, 이모티콘, 매거진 테스트 코드

- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
> [Feat#181] 채팅방 목록 querydsl 수정

- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
> [Feat#181] 채팅방 unreacount redis 적용

- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
> [Develop] main에 merge

- src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomService.java
- src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/global/exception/ProfileErrorCode.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/Matching.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/review/service/AdminReviewServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/user/domain/Profile.java
- src/main/java/com/mindmate/mindmate_server/user/dto/ProfileDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/user/service/ProfileServiceImpl.java
- src/test/java/com/mindmate/mindmate_server/payment/service/PaymentServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/point/service/ConcurrencyTests.java
- src/test/java/com/mindmate/mindmate_server/point/service/PointServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/profile/service/ProfileServiceTest.java
- src/test/java/com/mindmate/mindmate_server/review/service/AdminReviewServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/review/service/ReviewServiceTest.java
#179 
- 리뷰 테스트코드
- 프로필 테스트코드
- 포인트 테스트코드
- 결제 테스트코드
- 추가 변경 작업(매칭 및 프로필)
> [Test#179] 리뷰, 프로필, 포인트, 결제 테스트 및 추가 작업

- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
#188 
- 삭제한 채팅방 조회 시 리스너, 스피커 반대로 설정했음
> [Feat#188] 삭제한 채팅방 조회 querydsl 수정

- src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/WaitingUserResponse.java
> 😎 fix : 기본 프로필 익명 설정

- src/main/java/com/mindmate/mindmate_server/chat/repository/ChatRoomRepositoryImpl.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/MatchingDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/WaitingUserResponse.java
> [Develop] merge to main

- src/main/java/com/mindmate/mindmate_server/global/config/SecurityConfig.java
- src/main/java/com/mindmate/mindmate_server/matching/controller/AdminMatchingController.java
- src/main/java/com/mindmate/mindmate_server/matching/controller/MatchingController.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/Matching.java
- src/main/java/com/mindmate/mindmate_server/matching/domain/MatchingStatus.java
- src/main/java/com/mindmate/mindmate_server/matching/dto/PopularMatchingCategoryResponse.java
- src/main/java/com/mindmate/mindmate_server/matching/repository/MatchingRepository.java
- src/main/java/com/mindmate/mindmate_server/matching/service/AdminMatchingService.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingService.java
- src/main/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImpl.java
#208 
- 관리자 매칭 삭제 및 조회 기능
- 인기 매칭 카테고리 조회
> [Feat#208] 관리자 매칭 기능 추가

- src/main/java/com/mindmate/mindmate_server/chat/dto/ChatRoomDetailResponse.java
- src/main/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/mindmate/mindmate_server/global/service/DltMonitoringService.java
- src/test/java/com/mindmate/mindmate_server/MindmateServerApplicationTests.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatEventPublisherTest.java
- src/test/java/com/mindmate/mindmate_server/chat/service/ChatRoomServiceTest.java
- src/test/java/com/mindmate/mindmate_server/global/service/DltMonitoringServiceTest.java
- src/test/java/com/mindmate/mindmate_server/global/service/KafkaHealthServiceTest.java
- src/test/java/com/mindmate/mindmate_server/global/service/ResilientEventPublisherTest.java
#207 
1. dlt monitoring 테스트
2. 카프카 health 테스트
3. 채팅방 입장 시 리뷰 작성 여부 확인 및 테스트 코드 업데이트
4. redis 이벤트 발행 테스트
5. 카프카 resilient 이벤트 발행 테스트
> [Feat#207] global 테스트 코드 및 추가 정보 업데이트

- src/test/java/com/mindmate/mindmate_server/matching/service/AdminMatchingServiceTest.java
- src/test/java/com/mindmate/mindmate_server/matching/service/MatchingServiceImplTest.java
- src/test/java/com/mindmate/mindmate_server/matching/service/RedisMatchingServiceTest.java
- src/test/java/com/mindmate/mindmate_server/notification/service/AdminNotificationServiceTest.java
- src/test/java/com/mindmate/mindmate_server/notification/service/NotificationServiceTest.java
- src/test/java/com/mindmate/mindmate_server/user/service/UserServiceTest.java
> [Test#210] 테스트코드
